# Generated by Django 4.2.3 on 2024-03-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.CharField(default='Gulnara Saimassay', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='major_program',
            field=models.CharField(default='Computer Science', max_length=255),
            preserve_default=False,
        ),
    ]
