# Generated by Django 5.0.2 on 2024-02-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_student_options_alter_teacher_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=12, unique=True)),
                ("entity_id", models.CharField(max_length=20, unique=True)),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("registration_time", models.TimeField(auto_now_add=True)),
                ("really_attended", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("course_id", models.CharField(max_length=12, unique=True)),
                ("start_time", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=12, unique=True)),
                ("teacher_id", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentsCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=12, unique=True)),
                ("student_id", models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
