# Generated by Django 4.2.3 on 2024-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_student_advisor_student_major_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='Doctor of Science', max_length=255),
            preserve_default=False,
        ),
    ]
