# Generated by Django 4.2.3 on 2024-03-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_attendance_course_courseinstructor_studentscourses'),
        ('account', '0004_teacher_status'),
    ]

    operations = [
    ]
