# Generated by Django 4.2.3 on 2024-03-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge_20240312_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseInstructor',
        ),
        migrations.DeleteModel(
            name='StudentsCourses',
        ),
    ]
