# Generated by Django 4.2.3 on 2024-05-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_submitteddocument_specific_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitteddocument',
            name='accepted',
            field=models.IntegerField(choices=[(0, 'Not Checked'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
    ]
