# Generated by Django 4.2.3 on 2024-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.CharField(default='2+1+0', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='ects',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.DecimalField(decimal_places=0, default=45, max_digits=2),
            preserve_default=False,
        ),
    ]
