# Generated by Django 4.2.3 on 2024-03-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_attendance_delete_course_and_more'),
        ('attendance', '0002_course_credits_course_ects_course_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
            preserve_default=False,
        ),
    ]
