# Generated by Django 4.2.3 on 2024-03-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_schedule_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='manually_recorded',
            new_name='present',
        ),
        migrations.RenameField(
            model_name='attendancestatistics',
            old_name='absent_classes',
            new_name='absent_hours',
        ),
        migrations.RenameField(
            model_name='attendancestatistics',
            old_name='present_classes',
            new_name='present_hours',
        ),
        migrations.RenameField(
            model_name='attendancestatistics',
            old_name='total_classes',
            new_name='total_hours',
        ),
    ]
