# Generated by Django 4.2.3 on 2024-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_schedule_is_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_lecture',
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.CharField(default='01-N', max_length=10),
            preserve_default=False,
        ),
    ]
