# Generated by Django 4.2.3 on 2024-03-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='hours',
        ),
        migrations.AddField(
            model_name='attendancestatistics',
            name='p_hours',
            field=models.IntegerField(default=0),
        ),
    ]
