# Generated by Django 5.0.2 on 2024-04-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_course_hours_attendancestatistics_p_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='specific_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=7)),
                ('specific_course_id', models.IntegerField(default=0, unique=True)),
                ('group', models.IntegerField(default=0)),
                ('course_part', models.IntegerField(default=0)),
                ('course_start_time', models.TimeField()),
                ('course_start_day', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='course',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='student',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='student',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='exit_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ects',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='specific_course_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.CharField(default=100000000, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='weak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, default='100000000', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='students_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=9)),
                ('specific_course_id', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('student_id', 'specific_course_id')},
            },
        ),
        migrations.CreateModel(
            name='teachers_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=9)),
                ('specific_course_id', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('teacher_id', 'specific_course_id')},
            },
        ),
        migrations.DeleteModel(
            name='AttendanceStatistics',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='course',
            name='ECTS',
            field=models.IntegerField(default=5),
        ),
    ]
