# Generated by Django 5.0.2 on 2024-04-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_specific_course_remove_schedule_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_course',
            name='is_lecture',
            field=models.BooleanField(default=True),
        ),
    ]
