# Generated by Django 5.0.2 on 2024-04-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_att_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
