# Generated by Django 5.0.2 on 2024-04-28 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_specific_course_registration_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_of_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=6)),
                ('student_id', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='specific_course',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 12, 10, 41, 580058, tzinfo=datetime.timezone.utc)),
        ),
    ]
