# Generated by Django 5.0.2 on 2024-04-28 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_card_of_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_of_student',
            name='uid',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='specific_course',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 12, 24, 37, 838411, tzinfo=datetime.timezone.utc)),
        ),
    ]
