# Generated by Django 5.0.2 on 2024-05-01 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_card_of_student_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specific_course',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 22, 57, 28, 595376, tzinfo=datetime.timezone.utc)),
        ),
    ]
