# Generated by Django 5.0.2 on 2024-05-03 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specific_course',
            name='registration_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 16, 9, 15, 277052, tzinfo=datetime.timezone.utc)),
        ),
    ]
